### ISSUE TITLE
continuing error

### ISSUE THREAD

**Issue by 808rog** [bittorrent/btfs-dashboard#54] opened 2023-05-31 02:16 UTC
2023-05-30T20:07:10.628+0900    ERROR   dht     go-libp2p-kad-dht@v0.20.0/dht_net.go:47 ignoring incoming dht message while not in server mode

2023-05-31T08:11:50.875+0900    ERROR   autorelay       autorelay/autorelay.go:80       failed to start relay finder      {"error": "relayFinder already running"}

Please tell me how to solve it....

**Comment by CrCati** [comment] 2023-06-26 06:55
About '{"error": "relayFinder already running"}', this error message is caused by the go-libp2p library.  It should be fixed now.

**Closed** 2023-06-26 07:10 UTC
